// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKUR7jp4t1aA2lEUgawbTfbvXZh7yzPk',
    appId: '1:792248091068:web:67ef8fd7730fd7af50abb9',
    messagingSenderId: '792248091068',
    projectId: 'secondstuff-app-43851',
    authDomain: 'secondstuff-app-43851.firebaseapp.com',
    storageBucket: 'secondstuff-app-43851.firebasestorage.app',
    measurementId: 'G-RBXW37FE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3h4dKMTTfVadyVXJqik_zaQPFL0Hljrg',
    appId: '1:792248091068:android:76b060ce10d99d7250abb9',
    messagingSenderId: '792248091068',
    projectId: 'secondstuff-app-43851',
    storageBucket: 'secondstuff-app-43851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHWEO0jM3AIrb3qDcJIzCQF_dTMLLF0o',
    appId: '1:792248091068:ios:d932f7b9eba3dbbb50abb9',
    messagingSenderId: '792248091068',
    projectId: 'secondstuff-app-43851',
    storageBucket: 'secondstuff-app-43851.firebasestorage.app',
    iosBundleId: 'com.example.89Secondstufff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHWEO0jM3AIrb3qDcJIzCQF_dTMLLF0o',
    appId: '1:792248091068:ios:d932f7b9eba3dbbb50abb9',
    messagingSenderId: '792248091068',
    projectId: 'secondstuff-app-43851',
    storageBucket: 'secondstuff-app-43851.firebasestorage.app',
    iosBundleId: 'com.example.89Secondstufff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJKUR7jp4t1aA2lEUgawbTfbvXZh7yzPk',
    appId: '1:792248091068:web:4c9e8c322ca3109c50abb9',
    messagingSenderId: '792248091068',
    projectId: 'secondstuff-app-43851',
    authDomain: 'secondstuff-app-43851.firebaseapp.com',
    storageBucket: 'secondstuff-app-43851.firebasestorage.app',
    measurementId: 'G-R3PMKF1KC4',
  );
}
