// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_DSt9MadensPUgl61MBcTN4ObxymXAUg',
    appId: '1:59949075852:web:04a11daecc9bc7081bdaa9',
    messagingSenderId: '59949075852',
    projectId: 'mdul-6-cd',
    authDomain: 'mdul-6-cd.firebaseapp.com',
    storageBucket: 'mdul-6-cd.firebasestorage.app',
    measurementId: 'G-56SYR32RSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIDfAbb38uhEWace6EH9x-Cu807YZ9A8',
    appId: '1:59949075852:android:d0e44d9fb1cdec3a1bdaa9',
    messagingSenderId: '59949075852',
    projectId: 'mdul-6-cd',
    storageBucket: 'mdul-6-cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdR77dakweXH4p_NPEfr5tv41_90hCKc',
    appId: '1:59949075852:ios:0e8dff8bfd2646881bdaa9',
    messagingSenderId: '59949075852',
    projectId: 'mdul-6-cd',
    storageBucket: 'mdul-6-cd.firebasestorage.app',
    iosBundleId: 'com.example.89Secondstufff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdR77dakweXH4p_NPEfr5tv41_90hCKc',
    appId: '1:59949075852:ios:0e8dff8bfd2646881bdaa9',
    messagingSenderId: '59949075852',
    projectId: 'mdul-6-cd',
    storageBucket: 'mdul-6-cd.firebasestorage.app',
    iosBundleId: 'com.example.89Secondstufff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_DSt9MadensPUgl61MBcTN4ObxymXAUg',
    appId: '1:59949075852:web:04a11daecc9bc7081bdaa9',
    messagingSenderId: '59949075852',
    projectId: 'mdul-6-cd',
    authDomain: 'mdul-6-cd.firebaseapp.com',
    storageBucket: 'mdul-6-cd.firebasestorage.app',
    measurementId: 'G-56SYR32RSH',
  );
}
