// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3kgz22MM-oIxB1oLmSAnOYYH1VjrAmws',
    appId: '1:570092460540:web:771d29915acd68e6eefa79',
    messagingSenderId: '570092460540',
    projectId: 'secondstuff-app',
    authDomain: 'secondstuff-app.firebaseapp.com',
    storageBucket: 'secondstuff-app.firebasestorage.app',
    measurementId: 'G-HY810HRCJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQl8iVPsuyfIfYeKbZI06eGWsiA4rAIpQ',
    appId: '1:570092460540:android:1638664fae303f5feefa79',
    messagingSenderId: '570092460540',
    projectId: 'secondstuff-app',
    storageBucket: 'secondstuff-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDA8NpqdF256VswnC9ukDgQxv01syLFs',
    appId: '1:570092460540:ios:d99832b0c14e5727eefa79',
    messagingSenderId: '570092460540',
    projectId: 'secondstuff-app',
    storageBucket: 'secondstuff-app.firebasestorage.app',
    iosBundleId: 'com.example.89Secondstufff',
  );
}
